[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "process-issues-watcher"
version = "0.1.0"
dependencies = [
    "watchdog",
]

[project.scripts]
process-issues-watcher = "process_issues_watcher:main"
